-- AlterTable
ALTER TABLE `license` ADD COLUMN `ip` VARCHAR(191) NULL,
    ADD COLUMN `ipBoundEnabled` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `log` MODIFY `result` ENUM('VALID', 'NOT_FOUND', 'NOT_ACTIVE', 'EXPIRED', 'LICENSE_SCOPE_FAILED', 'IP_LIMIT_EXCEEDED', 'RATE_LIMIT_EXCEEDED', 'BOUND_IP_MISMATCH') NOT NULL;
